# NOTE: Please note that this is just an example of the advanced configuration for the KISS-ICP
# pipeline and it's not really meant to use for any particular dataset, is just to expose other
# options that are disabled by default
out_dir: "results"

data:
  deskew: True
  max_range: 100.0 # can be also changed in the CLI
  min_range: 0.0

mapping:
  voxel_size: 1.0 # <- optional
  max_points_per_voxel: 20

adaptive_threshold:
  fixed_threshold: 0.3 # <- optional, disables adaptive threshold
  # initial_threshold: 2.0
  # min_motion_th: 0.1

registration:
  max_num_iterations: 500 # <- optional
  convergence_criterion: 0.0001 # <- optional
  max_num_threads: 0 # <- optional, 0 means automatic
