name: C++ API

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jwlawson/actions-setup-cmake@v1.13
    - name: Configure CMake
      with:
        cmake-version: '3.22.x'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/cpp/kiss_icp
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
